name: "Local DNS"
description: "Custom DNS that receives local hosts fromm STDIN"
version: "1.0.0"
slug: "probably_giggle"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
stdin: true
startup: services
ports:
  8000/tcp: 8000


